### ISSUE TITLE
Is it possible to output image batch or image list?

### ISSUE THREAD

**Issue by cheezecrisp** [WASasquatch/ASTERR#7]
According to the reference code, this node can output one processed image. If I have more than one to output, how do I accomplish this? 
I tried to create a function that returns a list of pillow objects and got an error in the pil2tensor function.

**Comment by WASasquatch** [comment]
```
pil_images = []
for img in a:
    pil_images.append(tensor2pil(img))

#and

tensor_images = []
for img in pil_images:
    tensor_images.append(pil2tensor(img))

tensor_batch = torch.cat(tensor_images, dim=0)
```

**Comment by cheezecrisp** [comment]
> ```
> pil_images = []
> for img in a:
>     pil_images.append(tensor2pil(img))
> 
> #and
> 
> tensor_images = []
> for img in pil_images:
>     tensor_images.append(pil2tensor(img))
> 
> tensor_batch = torch.cat(tensor_images, dim=0)
> ```

Dose the node have to allow TORCH to work like this?

**Comment by WASasquatch** [comment]
```
pil_images = []
for img in a:
    pil_images.append(tensor2pil(img))

#and

tensor_images = []
for img in pil_images:
    tensor_images.append(pil2tensor(img))

tensor_batch = torch.cat(tensor_images, dim=0)
```

Yes
